name: CI/CD - React Client to GitHub Pages

on:
  push:
    branches:
      - main   # or 'master' if your repo uses that
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: ./client
        run: npm install

      # 4. Build React app
      - name: Build project
        working-directory: ./client
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
