name: CI/CD - MERN AI Text Summarizer

on:
  push:
    branches:
      - main   # or 'master' if that's your default
  pull_request:
  workflow_dispatch:

permissions:
  contents: write   # required for deploy

jobs:
  # ========== CI JOB ==========
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Server
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Run server tests
        working-directory: ./server
        run: npm test --if-present

      # Client
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Run client tests
        working-directory: ./client
        run: npm test --if-present

      - name: Build client
        working-directory: ./client
        run: npm run build

      # Debug: confirm build exists
      - name: List client build output
        run: ls -la ./client/build

      - name: Upload client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: ./client/build
          if-no-files-found: error   # ensures failure if build missing

  # ========== CD JOB ==========
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Download client build artifact
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: ./client/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
